"设置编码
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

"显示行号
set nu

"突出显示当前行
"set cul
"突出显示当前列
"set cuc

"启用鼠标
set mouse=a
set selection=exclusive
set selectmode=mouse,key

"括号匹配
set showmatch

"tab长度为4个空格
set tabstop=4
"自动缩进4个空格
set shiftwidth=4
"继承前一行的缩进方式
set autoindent

"用户级配置文件需要新建vim ~/.vimrc 且优先级高于系统配置文件
"vim生效命令
"source ~/.vimrc
